export const addDoc = jest.fn(() => ({}));
export const collection = jest.fn(() => ({}));
export const doc = jest.fn(() => ({}));
export const getDocs = jest.fn(() => ({}));
export const getFirestore = jest.fn(() => ({}));
export const increment = jest.fn(() => ({}));
export const onSnapshot = jest.fn();
export const query = jest.fn(() => ({}));
export const runTransaction = jest.fn(() => ({}));
export const setDoc = jest.fn(() => {});
export const updateDoc = jest.fn(() => ({}));
export const where = jest.fn(() => ({}));
